Update blank.yml

diff --git a/.github/workflows/blank.yml b/.github/workflows/blank.yml
--- a/.github/workflows/blank.yml
+++ b/.github/workflows/blank.yml
@@ -12,7 +12,17 @@ jobs:
     - name: Checkout
       uses: actions/checkout@v3
 
-    - name: Show branch name
+    - run: |
+        echo "Branch name is: ${{ github.ref_name }}" >> summary.txt
+
+  job2:
+    runs-on: [self-hosted, Linux, X64, docker]
+    steps:
+    - name: Check summary file
       run: |
-        
-        echo "Branch name is: ${{ github.ref_name }}"
+        if [[ -f summary.txt ]]; then
+          echo "exists"
+        else
+          echo "not found"
+          exit 1
+        fi
